version: '3'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db:
