# Generated by Django 4.0.1 on 2024-05-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0006_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blogs', verbose_name='фотография'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='sub_title',
            field=models.CharField(blank=True, max_length=264, null=True, verbose_name='подзаголовок'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=150, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='', verbose_name='комментарий'),
        ),
    ]
