# Generated by Django 4.0.1 on 2024-05-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0007_alter_blog_content_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcologicalTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='topics',
            field=models.ManyToManyField(related_name='blogs', to='app_blog.EcologicalTopic'),
        ),
    ]
